apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-m6bp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-m6bp@sha256:5715751b624b6ec60675bad87bde18eb41fc80acf2113d80e7a2c98bb32133fb
        name: my-nodejs
        resources: {}
status: {}
